name: Auto-Response for Update Issues

on:
  issues:
    types: [opened]

jobs:
  respond-to-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue contains update-related text
        id: check
        run: |
          echo "Checking issue body for update conditions..."
          ISSUE_BODY="${{ github.event.issue.body }}"
          if echo "$ISSUE_BODY" | grep -iEq 'stable|update stable version|stable=1\.[0-9]+\.[0-9]+'; then
            echo "match=true" >> $GITHUB_OUTPUT
          else
            echo "match=false" >> $GITHUB_OUTPUT
          fi
      - name: Post a response
        if: steps.check.outputs.match == 'true'
        uses: peter-evans/create-or-update-comment@v5
        with:
          token: ${{ secrets.REPO_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Die aktuelle beta releases enthalten noch nicht ausreichend genug getestete Features
            und evtl. weitere Probleme, welche nicht für ein stable Release geeignet sind.
            Ich werde dann bei Gelegenheit eine geeignete Version über das Developer Portal freischalten.
